name: Docs Merge Trigger
# This job completes when it detects a successful merge to main, with changes that should trigger generate-mkdocs-website.yml

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'docs/*'
      - 'mkdocs.yml'

jobs:
  check_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Successful merge detected.
