name: Merge Trigger

on:
  pull_request:
    types:
      - closed

jobs:
  check_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Successful merge detected.
